CREATE TABLE BOOKS_T(BOOK_ID INT PRIMARY KEY, BOOK_NAME VARCHAR(50), BOOK_PRICE INT);

CREATE TABLE BOOK_STOCKS_T(STOCK_ID INT PRIMARY KEY, BOOK_ID INT, BOOK_STOCK INT);

CREATE TABLE ACCOUNTS_T(ACCOUNT_ID INT PRIMARY KEY, USER_ID INT, BALANCE INT);

CREATE TABLE USERS_T(USER_ID INT PRIMARY KEY, USER_NAME VARCHAR(50), USER_PASS VARCHAR(20));